media: assets/img
content:
  - name: posts
    label: Posts
    path: _posts
    type: collection
    view:
      fields: [ title, date ]
    fields:
    - name: layout
      label: Page layout
      type: select
      options:
        values:
        - value: post
          label: Post
        - value: redirect
          label: Redirect
        - value: article
          label: Article
    - name: title
      label: Title
      type: string
    - name: credits
      label: Credits/Description
      type: string
    - name: category
      label: Category
      type: select
      options:
        values:
        - value: post
          label: Post
        - value: redirect
          label: Redirect
        - value: article
          label: Article
    - name: relink
      label: Redirect link (if redirect)
      type: string
    - name: hidden
      label: Hide post
      type: boolean
    - name: preview
      label: Preview image
      type: string
    - name: body
      label: Body
      type: rich-text
    - name: date
      label: Date
      type: date